services:
    # Servicio de la Aplicación Laravel (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rrhh-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - rrhh-network
    # Servicio del Servidor Web (Nginx)
    nginx:
        image: nginx:1.25-alpine
        container_name: rrhh-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mariadb
        networks:
            - rrhh-network
    # Servicio de Base de Datos
    mariadb:
        image: 'mariadb:11'
        container_name: rrhh-db
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'rrhh-mariadb-data:/var/lib/mysql'
        networks:
            - rrhh-network
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
networks:
    rrhh-network:
        driver: bridge
volumes:
    rrhh-mariadb-data:
        driver: local
