<?php

return [
    'categorias' => [
        'CAT. 1',
        'CAT. 3',
        'CAT. 5',
        'CAT. 6',
        'CAT. 7',
        'CAT. 8',
        'CAT. 9',
        'CAT. 10',
        'CAT. 12',
        'CAT. 13',
        'CAT. 14',
        'CAT. 15',
        'CAT. 16',
        'CAT. 18',
        'CAT. "A"',
        'CAT. "B"',
        'CAT. I "B"',
        'S/CATEGORIA',
    ],

    'sectores' => [
        '01 - Administración',
        '02 - Redes',
        '03 - Servicios de Sepelios',
        '04 - U.C.I.M.',
        '06 - Telecomunicaciones',
        '07 - Gabinete de Enfermería',
    ],

    'puestos' => [
        'Ayudante de Oficio',
        'Ayudante de Oficio - Especializado',
        'Ayudante de Oficio - Toma Estado',
        'Ayudante Técnico',
        'Ayudante Técnico Especializado',
        'Ayudante Administrativo',
        'Auxiliar',
        'Auxiliar Administrativo',
        'Capataz',
        'Capataz de Redes',
        'Chofer',
        'Contadora',
        'Coordinador General',
        'Coordinador de Servicios Sociales',
        'Encargado de Compras Generales',
        'Encargado de Conexiones',
        'Encargado de Facturación y Sistemas',
        'Encargado de Gestión Humana',
        'Encargado de Laboratorio',
        'Encargado de Operaciones',
        'Encargado de Sistemas SCADA y Pro',
        'Enfermera / Enfermero',
        'Guardia de Reclamos',
        'Ingeniero',
        'Ingeniero de Redes',
        'Jefa de Mesa de Entradas',
        'Jefe Contable',
        'Jefe de Distribución',
        'Jefe de Redes',
        'Oficial',
        'Oficial de Redes',
        'Peón General de Redes',
        'Peón General de Redes - Toma Estado',
        'Relevante de Guardia',
        'Tablerista',
    ],
]; 